version: '3'

services:
  bot:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/coin-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
